<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seasons [ 
    <!ELEMENT seasons (season+)>
    <!ELEMENT season (spring+, summer+, autumn+, winter+)>
    <!ELEMENT spring (#PCDATA)>
     <!ELEMENT summer (#PCDATA)>
    <!ELEMENT autumn (#PCDATA)>
    <!ELEMENT winter (#PCDATA)>
]>
<seasons>
    <season>
        <spring>Tomato</spring>
        <summer>Zucchini</summer>
        <autumn>Lettuce</autumn>
        <winter>zucchini</winter>
    </season>
        <season>
        <spring>Radish</spring>
        <summer>Pumpkin</summer>
        <autumn>Pumpkin</autumn>
        <winter>Cabbage</winter>
    </season>
        <season>
        <spring>Green bean</spring>
        <summer>Garlic</summer>
        <autumn>Spinach</autumn>
        <winter>cauliflower</winter>
    </season>
        <season>
        <spring>Lettuce</spring>
        <summer>Lettuce</summer>
        <autumn>Chard</autumn>
        <winter>endive</winter>
    </season>
        <season>
        <spring>Onions</spring>
        <summer>Cucumber</summer>
        <autumn>Leek</autumn>
        <winter>escarole</winter>
    </season>
        <season>
        <spring>Pumpkin</spring>
        <summer>Carrot</summer>
        <autumn>Cabbage</autumn>
        <winter>aubergines</winter>
    </season>
</seasons>