<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fruits [ 
    <!ELEMENT fruits (fruit+)>
    <!ELEMENT fruit (name+, season+)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT season (#PCDATA)>
]>
<!--fruits-->
<fruits>
    <fruit>
        <name>Apricot</name>
        <season>Spring</season>
    </fruit>
    <fruit>
        <name>Cherry</name>
        <season>Spring</season>
    </fruit>
    <fruit>
        <name>Plum</name>
        <season>Spring</season>
    </fruit>
    <fruit>
        <name>Strawberry</name>
        <season>Spring</season>
    </fruit>
    <fruit>
        <name>Peach</name>
        <season>Spring</season>
    </fruit>
    <fruit>
        <name>Melon</name>
        <season>Spring</season>
    </fruit>
    <fruit>
        <name>Peach</name>
        <season>Summer</season>
    </fruit>
    <fruit>
        <name>Raspberry</name>
        <season>Summer</season>
    </fruit>
    <fruit>
        <name>Mango</name>
        <season>Summer</season>
    </fruit>
    <fruit>
        <name>Nectarine</name>
        <season>Summer</season>
    </fruit>
    <fruit>
        <name>Watermelon</name>
        <season>Summer</season>
    </fruit>
    <fruit>
        <name>Cherry</name>
        <season>Summer</season>
    </fruit>
    <fruit>
        <name>Grape</name>
        <season>Autumn</season>
    </fruit>
    <fruit>
        <name>Persimmon</name>
        <season>Autumn</season>
    </fruit>
    <fruit>
        <name>Tangerine</name>
        <season>Autumn</season>
    </fruit>
        <fruit>
        <name>Apple</name>
        <season>Autumn</season>
    </fruit>
    <fruit>
        <name>Pear</name>
        <season>Autumn</season>
    </fruit>
    <fruit>
        <name>Pomegranate</name>
        <season>Autumn</season>
    </fruit>
        <fruit>
        <name>Kiwi</name>
        <season>Winter</season>
    </fruit>
    <fruit>
        <name>Lemon</name>
        <season>Winter</season>
    </fruit>
    <fruit>
        <name>Orange</name>
        <season>Winter</season>
    </fruit>
        <fruit>
        <name>Tangerine</name>
        <season>Winter</season>
    </fruit>
    <fruit>
        <name>Persimmon</name>
        <season>Winter</season>
    </fruit>
    <fruit>
        <name>Apple</name>
        <season>Winter</season>
    </fruit>
</fruits>


