<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seasons [ 
    <!ELEMENT seasons (season+)>
    <!ELEMENT season (spring+, summer+, autumn+, winter+)>
    <!ELEMENT spring (#PCDATA)>
     <!ELEMENT summer (#PCDATA)>
    <!ELEMENT autumn (#PCDATA)>
    <!ELEMENT winter (#PCDATA)>
]>
<seasons>
    <season>
        <spring>Apricot</spring>
        <summer>Peach</summer>
        <autumn>Grape</autumn>
        <winter>Kiwi</winter>
    </season>
    <season>
        <spring>Cherry</spring>
        <summer>Raspberry</summer>
        <autumn>Persimmon</autumn>
        <winter>Lemon</winter>
    </season>
    <season>
        <spring>Strawberry</spring>
        <summer>Mango</summer>
        <autumn>Pear</autumn>
        <winter>Orange</winter>
    </season>
    <season>
        <spring>Peach</spring>
        <summer>Nectarine</summer>
        <autumn>Tangerine</autumn>
        <winter>Tangerine</winter>
    </season>
    <season>
        <spring>Melon</spring>
        <summer>Watermelon</summer>
        <autumn>Apple</autumn>
        <winter>Persimmon</winter>
    </season>
    <season>
        <spring>Plum</spring>
        <summer>Cherry</summer>
        <autumn>Pear</autumn>
        <winter>Apple</winter>
    </season>
    
    <season>
        <spring>Tomato</spring>
        <summer>Zucchini</summer>
        <autumn>Lettuce</autumn>
        <winter>zucchini</winter>
    </season>
    <season>
        <spring>Radish</spring>
        <summer>Pumpkin</summer>
        <autumn>Pumpkin</autumn>
        <winter>Cabbage</winter>
    </season>
    <season>
        <spring>Green bean</spring>
        <summer>Garlic</summer>
        <autumn>Spinach</autumn>
        <winter>cauliflower</winter>
    </season>
    <season>
        <spring>Lettuce</spring>
        <summer>Lettuce</summer>
        <autumn>Chard</autumn>
        <winter>endive</winter>
    </season>
    <season>
        <spring>Onions</spring>
        <summer>Cucumber</summer>
        <autumn>Leek</autumn>
        <winter>escarole</winter>
    </season>
    <season>
        <spring>Pumpkin</spring>
        <summer>Carrot</summer>
        <autumn>Cabbage</autumn>
        <winter>aubergines</winter>
    </season>
</seasons>
